export const PERMISSIONS = {
  CREATE_GROUP: 'groups.create',
  DELETE_GROUP: 'groups.delete',
  EDIT_GROUP: 'groups.edit',
  VIEW_GROUP: 'groups.view',
  VIEW_PERMISSIONS: 'permissions.view',
  VIEW_STATISTIC: 'statistic.view',
  VIEW_USERS: 'users.view',
  EDIT_USERS: 'users.edit',
  CREATE_AUTHORS: 'authors.create',
  EDIT_AUTHORS: 'authors.edit',
  DELETE_AUTHORS: 'authors.delete',
  CREATE_BOOKS: 'books.create',
  EDIT_BOOKS: 'books.edit',
  DELETE_BOOKS: 'books.delete',
  CREATE_GENRES: 'genres.create',
  EDIT_GENRES: 'genres.edit',
  DELETE_GENRES: 'genres.delete',
  VIEW_ORDERS: 'orders.view',
  CREATE_ORDERS: 'orders.create',
  EDIT_ORDERS: 'orders.edit',
  VIEW_CART: 'cart.view',
  ADD_CART: 'cart.add',
  EDIT_CART: 'cart.edit',
  DELETE_CART: 'cart.delete',
  UPLOAD_CART: 'files.upload',
}
